function selectedRow = selectMuscle()
    muscles = { ...
        'Acromiodeltoideus', 'Anconeus', ...
        'Abductor pollicis longus O-R', 'Abductor pollicis longus R-I', ...
        'Biceps brachii', 'Brachioradialis O-R', 'Brachioradialis R-I', ...
        'Brachialis', 'Coracobrachialis', 'Extensor carpi radialis O-R', ...
        'Extensor carpi radialis R-I', 'Extensor carpi ulnaris O-R', ...
        'Extensor carpi ulnaris R-I', 'Extensor digitorum communis 2 O-R', ...
        'Extensor digitorum communis 2 R-I', 'Extensor digitorum communis 3 O-R', ...
        'Extensor digitorum communis 3 R-I', 'Extensor digitorum communis 4 O-R', ...
        'Extensor digitorum communis 4 R-I', 'Extensor digitorum communis 5 O-R', ...
        'Extensor digitorum communis 5 R-I', 'Extensor digitorum lateralis 2 O-R', ...
        'Extensor digitorum lateralis 2 R-I', 'Extensor digitorum lateralis 3 O-R', ...
        'Extensor digitorum lateralis 3 R-I', 'Extensor digitorum lateralis 4 O-R', ...
        'Extensor digitorum lateralis 4 R-I', 'Extensor digitorum lateralis 5 O-R', ...
        'Extensor digitorum lateralis 5 R-I', 'Extensor pollicis longus 1 O-R', ...
        'Extensor pollicis longus 1 R-I', 'Extensor pollicis longus 2 O-R', ...
        'Extensor pollicis longus 2 R-I', 'Epitrochlearis', 'Flexor carpi radialis O-R', ...
        'Flexor carpi radialis R-I', 'Flexor carpi ulnaris O-R', 'Flexor carpi ulnaris R-I', ...
        'Flexor digitorum profundus 1 O-R', 'Flexor digitorum profundus 1 R-I', ...
        'Flexor digitorum profundus 2 O-R', 'Flexor digitorum profundus 2 R-I', ...
        'Flexor digitorum profundus 3 O-R', 'Flexor digitorum profundus 3 R-I', ...
        'Flexor digitorum profundus 4 O-R', 'Flexor digitorum profundus 4 R-I', ...
        'Flexor digitorum profundus 5 O-R', 'Flexor digitorum profundus 5 R-I', ...
        'Flexor digitorum superficialis 2 O-R', 'Flexor digitorum superficialis 2 R-I', ...
        'Flexor digitorum superficialis 3 O-R', 'Flexor digitorum superficialis 3 R-I', ...
        'Flexor digitorum superficialis 4 O-R', 'Flexor digitorum superficialis 4 R-I', ...
        'Flexor digitorum superficialis 5 O-R', 'Flexor digitorum superficialis 5 R-I', ...
        'Infraspinatus O-R', 'Infraspinatus R-I', 'Palmaris longus 1 O-R', ...
        'Palmaris longus 1 R-I', 'Palmaris longus 2 O-R', 'Palmaris longus 2 R-I', ...
        'Palmaris longus 3 O-R', 'Palmaris longus 3 R-I', 'Palmaris longus 4 O-R', ...
        'Palmaris longus 4 R-I', 'Palmaris longus 5 O-R', 'Palmaris longus 5 R-I', ...
        'Pronator teres', 'Spinodeltoideus', 'Supraspinatus', 'Subscapularis', ...
        'Teres major', 'Triceps brachii lateralis', 'Triceps brachii long', ...
        'Triceps brachii medial', 'Teres minor' ...
    };

    uniqueMuscles = unique(cellfun(@(x) regexprep(x, ' O-R| R-I', ''), muscles, 'UniformOutput', false));
    [indx, tf] = listdlg('ListString', uniqueMuscles, 'SelectionMode', 'single', 'PromptString', 'Select a muscle for visualization in 2D and 3D:', 'ListSize', [300, 600]);
    
    if tf == 1
        selectedMuscle = uniqueMuscles{indx};
        matchingRows = find(contains(muscles, selectedMuscle));
        selectedRow = min(matchingRows);
        fprintf('Selected Muscle Visualization in 2D and 3D: %s\n', selectedMuscle);
        fprintf('Row Number: %d\n', selectedRow);
    else
        disp('No muscle selected.');
        selectedRow = [];
    end
end
